import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/app_models.dart';
final onboardedProvider=StateProvider<bool>((ref)=>false); final signedInProvider=StateProvider<bool>((ref)=>false); final tabProvider=StateProvider<int>((ref)=>0);
final settingsProvider=StateNotifierProvider<SettingsVm,UserSettings>((ref)=>SettingsVm()); class SettingsVm extends StateNotifier<UserSettings>{SettingsVm():super(const UserSettings()); void dark(bool v)=>state=state.copyWith(darkMode:v); void notifications(bool v)=>state=state.copyWith(notifications:v); void language(String v)=>state=state.copyWith(language:v);}
final medicinesProvider=StateNotifierProvider<MedicineVm,List<Medicine>>((ref)=>MedicineVm()); class MedicineVm extends StateNotifier<List<Medicine>>{MedicineVm():super([Medicine(id:'m1',userId:'demo',name:'Vitamin D3',dosage:'1 capsule',time:'8:00 AM'),Medicine(id:'m2',userId:'demo',name:'Metformin',dosage:'500 mg',time:'2:00 PM')]); void upsert(Medicine m)=>state=[...state.where((e)=>e.id!=m.id),m]; void delete(String id)=>state=[for(final m in state) if(m.id!=id)m]; void toggle(String id)=>state=[for(final m in state) m.id==id?m.copyWith(taken:!m.taken):m];}
final appointmentsProvider=StateNotifierProvider<AppointmentVm,List<Appointment>>((ref)=>AppointmentVm()); class AppointmentVm extends StateNotifier<List<Appointment>>{AppointmentVm():super([Appointment(id:'a1',userId:'demo',doctorName:'Dr. Sarah Wilson',clinicName:'City Cardiology',dateTime:DateTime.now().add(const Duration(days:1,hours:2)),notes:'Bring latest reports')]); void upsert(Appointment a)=>state=[...state.where((e)=>e.id!=a.id),a]..sort((a,b)=>a.dateTime.compareTo(b.dateTime)); void delete(String id)=>state=[for(final a in state) if(a.id!=id)a];}
final waterProvider=StateNotifierProvider<WaterVm,WaterIntake>((ref)=>WaterVm()); class WaterVm extends StateNotifier<WaterIntake>{WaterVm():super(WaterIntake(id:DateTime.now().toIso8601String().substring(0,10),userId:'demo',glasses:4)); void add()=>state=state.copyWith(glasses:state.glasses+1); void remove()=>state=state.copyWith(glasses:state.glasses>0?state.glasses-1:0); void reset()=>state=state.copyWith(glasses:0);}
final healthRecordsProvider=StateNotifierProvider<HealthVm,List<HealthRecord>>((ref)=>HealthVm()); class HealthVm extends StateNotifier<List<HealthRecord>>{HealthVm():super([HealthRecord(id:'h1',userId:'demo',type:'Weight',value:72,unit:'kg'),HealthRecord(id:'h2',userId:'demo',type:'Heart rate',value:76,unit:'bpm')]); void add(HealthRecord r)=>state=[r,...state];}
final reportsProvider=StateNotifierProvider<ReportVm,List<MedicalReport>>((ref)=>ReportVm()); class ReportVm extends StateNotifier<List<MedicalReport>>{ReportVm():super([]); void add(MedicalReport r)=>state=[r,...state]; void delete(String id)=>state=[for(final r in state) if(r.id!=id)r];}
final emergencyProvider=StateProvider<EmergencyProfile>((ref)=>EmergencyProfile(userId:'demo',contactName:'Family Contact',contactPhone:'911',bloodGroup:'O+'));
const tips=[HealthTip('Diet Tips','Hydrate early','Start your day with a glass of water and a balanced breakfast.'),HealthTip('Exercise Tips','Move gently','A 10-minute walk after meals can support digestion and energy.'),HealthTip('Mental Health Tips','Pause to breathe','Try four slow breaths when you feel stressed.'),HealthTip('General Wellness','Sleep routine','Keep a consistent sleep and wake time when possible.')];
