import 'package:cloud_firestore/cloud_firestore.dart';
DateTime _dt(dynamic v)=>v is Timestamp?v.toDate():DateTime.tryParse('$v')??DateTime.now();
Map<String,dynamic> stamp(DateTime c,DateTime u)=>{'createdAt':Timestamp.fromDate(c),'updatedAt':Timestamp.fromDate(u)};
class AppUser{AppUser({required this.id,required this.email,required this.name,this.createdAt,this.updatedAt});final String id,email,name;final DateTime? createdAt,updatedAt;factory AppUser.fromMap(String id,Map<String,dynamic> m)=>AppUser(id:id,email:m['email']??'',name:m['name']??'Friend',createdAt:_dt(m['createdAt']),updatedAt:_dt(m['updatedAt']));Map<String,dynamic> toMap()=>{'email':email,'name':name,...stamp(createdAt??DateTime.now(),updatedAt??DateTime.now())};AppUser copyWith({String? name})=>AppUser(id:id,email:email,name:name??this.name,createdAt:createdAt,updatedAt:DateTime.now());}
class Medicine{Medicine({required this.id,required this.userId,required this.name,required this.dosage,required this.time,this.foodTiming='After food',this.notes='',this.active=true,this.taken=false,DateTime? createdAt,DateTime? updatedAt}):createdAt=createdAt??DateTime.now(),updatedAt=updatedAt??DateTime.now();final String id,userId,name,dosage,time,foodTiming,notes;final bool active,taken;final DateTime createdAt,updatedAt;factory Medicine.fromMap(String id,Map<String,dynamic> m)=>Medicine(id:id,userId:m['userId']??'',name:m['name']??'',dosage:m['dosage']??'',time:m['time']??'',foodTiming:m['foodTiming']??'After food',notes:m['notes']??'',active:m['active']??true,taken:m['taken']??false,createdAt:_dt(m['createdAt']),updatedAt:_dt(m['updatedAt']));Map<String,dynamic> toMap()=>{'userId':userId,'name':name,'dosage':dosage,'time':time,'foodTiming':foodTiming,'notes':notes,'active':active,'taken':taken,...stamp(createdAt,updatedAt)};Medicine copyWith({bool? taken,bool? active})=>Medicine(id:id,userId:userId,name:name,dosage:dosage,time:time,foodTiming:foodTiming,notes:notes,active:active??this.active,taken:taken??this.taken,createdAt:createdAt,updatedAt:DateTime.now());}
class Appointment{Appointment({required this.id,required this.userId,required this.doctorName,required this.clinicName,required this.dateTime,this.notes='',DateTime? createdAt,DateTime? updatedAt}):createdAt=createdAt??DateTime.now(),updatedAt=updatedAt??DateTime.now();final String id,userId,doctorName,clinicName,notes;final DateTime dateTime,createdAt,updatedAt;factory Appointment.fromMap(String id,Map<String,dynamic> m)=>Appointment(id:id,userId:m['userId']??'',doctorName:m['doctorName']??'',clinicName:m['clinicName']??'',dateTime:_dt(m['dateTime']),notes:m['notes']??'',createdAt:_dt(m['createdAt']),updatedAt:_dt(m['updatedAt']));Map<String,dynamic> toMap()=>{'userId':userId,'doctorName':doctorName,'clinicName':clinicName,'dateTime':Timestamp.fromDate(dateTime),'notes':notes,...stamp(createdAt,updatedAt)};}
class MedicalReport{MedicalReport({required this.id,required this.userId,required this.title,required this.category,required this.fileUrl,this.notes='',DateTime? uploadedAt}):uploadedAt=uploadedAt??DateTime.now();final String id,userId,title,category,fileUrl,notes;final DateTime uploadedAt;Map<String,dynamic> toMap()=>{'userId':userId,'title':title,'category':category,'fileUrl':fileUrl,'notes':notes,'uploadedAt':Timestamp.fromDate(uploadedAt)};factory MedicalReport.fromMap(String id,Map<String,dynamic> m)=>MedicalReport(id:id,userId:m['userId']??'',title:m['title']??'',category:m['category']??'Other',fileUrl:m['fileUrl']??'',notes:m['notes']??'',uploadedAt:_dt(m['uploadedAt']));}
class HealthRecord{HealthRecord({required this.id,required this.userId,required this.type,required this.value,required this.unit,DateTime? recordedAt}):recordedAt=recordedAt??DateTime.now();final String id,userId,type,unit;final double value;final DateTime recordedAt;Map<String,dynamic> toMap()=>{'userId':userId,'type':type,'value':value,'unit':unit,'recordedAt':Timestamp.fromDate(recordedAt)};}
class WaterIntake{WaterIntake({required this.id,required this.userId,this.glasses=0,this.goal=8,DateTime? date}):date=date??DateTime.now();final String id,userId;final int glasses,goal;final DateTime date;double get progress=>goal==0?0:glasses/goal;Map<String,dynamic> toMap()=>{'userId':userId,'glasses':glasses,'goal':goal,'date':Timestamp.fromDate(date)};WaterIntake copyWith({int? glasses})=>WaterIntake(id:id,userId:userId,glasses:glasses??this.glasses,goal:goal,date:date);}
class EmergencyProfile{EmergencyProfile({required this.userId,this.contactName='',this.contactPhone='',this.bloodGroup='',this.allergies='',this.conditions='',this.medications='',this.notes=''});final String userId,contactName,contactPhone,bloodGroup,allergies,conditions,medications,notes;Map<String,dynamic> toMap()=>{'userId':userId,'contactName':contactName,'contactPhone':contactPhone,'bloodGroup':bloodGroup,'allergies':allergies,'conditions':conditions,'medications':medications,'notes':notes};}
class HealthTip{const HealthTip(this.category,this.title,this.body);final String category,title,body;}
class UserSettings{const UserSettings({this.darkMode=false,this.notifications=true,this.language='English'});final bool darkMode,notifications;final String language;UserSettings copyWith({bool? darkMode,bool? notifications,String? language})=>UserSettings(darkMode:darkMode??this.darkMode,notifications:notifications??this.notifications,language:language??this.language);}
